//! Snapshot helpers — typed accessors over the raw FFI snapshot structs.
//!
//! The raw `BotWorldSnapshot` / `BotUnitSnapshot` types are generated by bindgen
//! and are plain C structs. This module provides ergonomic Rust accessors.

#![forbid(unsafe_code)]

use crate::{BotUnitSnapshot, BotWorldSnapshot, SpellId, UnitHandle};

/// Extension methods for `BotWorldSnapshot`.
pub trait WorldSnapshotExt {
    fn self_unit(&self) -> &BotUnitSnapshot;
    fn self_hp_pct(&self) -> f32;
    fn self_mana_pct(&self) -> f32;
    fn group_iter(&self) -> impl Iterator<Item = UnitHandle> + '_;
    fn in_instance(&self) -> bool;
}

impl WorldSnapshotExt for BotWorldSnapshot {
    fn self_unit(&self) -> &BotUnitSnapshot {
        &self.self_
    }

    fn self_hp_pct(&self) -> f32 {
        let u = self.self_unit();
        if u.max_health == 0 {
            return 1.0;
        }
        u.health as f32 / u.max_health as f32
    }

    fn self_mana_pct(&self) -> f32 {
        let u = self.self_unit();
        if u.max_mana == 0 {
            return 1.0;
        }
        u.mana as f32 / u.max_mana as f32
    }

    fn group_iter(&self) -> impl Iterator<Item = UnitHandle> + '_ {
        self.group_members[..self.group_size as usize]
            .iter()
            .copied()
            .filter(|&h| h != 0)
    }

    fn in_instance(&self) -> bool {
        self.instance_id != 0
    }
}

/// Extension methods for `BotUnitSnapshot`.
pub trait UnitSnapshotExt {
    fn hp_pct(&self) -> f32;
    fn mana_pct(&self) -> f32;
    fn rage(&self) -> u32;
    fn energy(&self) -> u32;
    fn is_casting_spell(&self, spell_id: SpellId) -> bool;
    fn cast_progress(&self) -> f32;
}

impl UnitSnapshotExt for BotUnitSnapshot {
    fn hp_pct(&self) -> f32 {
        if self.max_health == 0 {
            return 1.0;
        }
        self.health as f32 / self.max_health as f32
    }

    fn mana_pct(&self) -> f32 {
        if self.max_mana == 0 {
            return 1.0;
        }
        self.mana as f32 / self.max_mana as f32
    }

    /// Current rage (only valid for warriors and druids in bear/cat form).
    fn rage(&self) -> u32 {
        if self.power_type == 1 { self.mana } else { 0 }
    }

    /// Current energy (only valid for rogues and druids in cat form).
    fn energy(&self) -> u32 {
        if self.power_type == 3 { self.mana } else { 0 }
    }

    fn is_casting_spell(&self, spell_id: SpellId) -> bool {
        self.is_casting && self.casting_spell_id == spell_id.raw()
    }

    fn cast_progress(&self) -> f32 {
        self.casting_progress
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn unit_at_hp(hp: u32, max_hp: u32) -> BotUnitSnapshot {
        BotUnitSnapshot {
            health: hp,
            max_health: max_hp,
            ..BotUnitSnapshot::default()
        }
    }

    #[test]
    fn hp_pct_correct() {
        let u = unit_at_hp(500, 1000);
        assert!((u.hp_pct() - 0.5).abs() < f32::EPSILON);
    }

    #[test]
    fn hp_pct_zero_max_returns_one() {
        let u = unit_at_hp(0, 0);
        assert_eq!(u.hp_pct(), 1.0);
    }
}
