/// Main tick logic — called from `playerbot_update`.
///
/// Sequence per tick:
///   1. Refresh snapshot (one C++ call)
///   2. Throttled refresh of nearby/attacker lists
///   3. Process push events (update encounter FSM, blackboard)
///   4. Build TickContext
///   5. Run the BT tree
///   6. Advance timers
use crate::{
    bot::state::BotState,
    engine::context::TickContext,
};

const ATTACKERS_REFRESH_INTERVAL_MS:  u64 = 500;
const NEARBY_REFRESH_INTERVAL_MS:     u64 = 1000;

pub fn tick(bot: &mut BotState, elapsed_ms: u32, minimal: bool) {
    // 1. Refresh snapshot (always — one C++ call)
    bot.snap = bot.interface.get_snapshot();
    let now_ms = bot.snap.server_time_ms;

    // 2. Throttled attacker/nearby refresh
    if !minimal && now_ms.saturating_sub(bot.last_attackers_refresh_ms) >= ATTACKERS_REFRESH_INTERVAL_MS {
        bot.attackers = bot.interface.get_nearby_units(40.0, true);
        bot.last_attackers_refresh_ms = now_ms;
    }
    if !minimal && now_ms.saturating_sub(bot.last_nearby_refresh_ms) >= NEARBY_REFRESH_INTERVAL_MS {
        bot.nearby_units = bot.interface.get_nearby_units(60.0, false);
        bot.last_nearby_refresh_ms = now_ms;
    }

    // 3. Process push events
    process_events(bot, now_ms);

    // 4. Build TickContext and run BT
    // We need to split borrows: interface + blackboard + timers can't all be borrowed at once
    // through BotState. We use a local snapshot copy for the context.
    let snap = &bot.snap;
    let attackers: &[u64] = &bot.attackers;
    let nearby: &[u64] = &bot.nearby_units;

    let group_state = bot.group_state.as_ref()
        .and_then(|arc| arc.try_read().ok().map(|_| ()));

    let ctx_group = bot.group_state.as_ref()
        .and_then(|arc| arc.try_read().ok());

    // Build the context referencing bot's mutable fields
    // SAFETY: root_tree does not access blackboard/timers/interface through BotState,
    // only through TickContext which we construct here with explicit borrows.
    let bot_handle = bot.handle;
    let mut ctx = TickContext {
        snap,
        nearby,
        attackers,
        group_state: ctx_group.as_deref(),
        interface:   bot.interface.as_ref(),
        blackboard:  &mut bot.blackboard,
        timers:      &mut bot.timers,
        server_time_ms: now_ms,
        elapsed_ms,
        minimal,
        bot_handle,
    };

    // We need to tick the tree but root_tree is in bot. Use a pointer to avoid
    // the double-borrow. This is safe because root_tree only reads its own
    // internal node state (Cell-based throttle timestamps) and writes through ctx.
    let tree_ptr = &*bot.root_tree as *const dyn crate::engine::bt_nodes::BtNode;
    // SAFETY: root_tree is alive for the duration of this tick; ctx does not hold
    // references into root_tree; root_tree does not hold references into ctx.
    let result = unsafe { (*tree_ptr).tick(&mut ctx) };
    let _ = result; // Running is handled by blackboard state across ticks

    // 6. Advance timers
    bot.timers.advance(now_ms);
}

fn process_events(bot: &mut BotState, now_ms: u64) {
    while let Some(event) = bot.events.pop_front() {
        use crate::bot::events::BotEvent;
        match event {
            BotEvent::UnitDied { victim, killer: _ } => {
                // If our current target died, clear it
                if Some(victim) == {
                    let h = bot.snap.self_unit().current_target;
                    if h == 0 { None } else { Some(h) }
                } {
                    // Target will be cleared naturally by next snapshot refresh
                }
                // Track add deaths for encounter FSMs
                use crate::engine::blackboard::{Key, Value};
                if let Some(count) = bot.blackboard.get_u32(Key::AddCount) {
                    if count > 0 {
                        bot.blackboard.set(Key::AddCount, Value::U32(count - 1));
                    }
                }
            }
            BotEvent::DamageTaken { damage: _, spell_id: _, dealer: _ } => {
                // Handled by emergency flee subtree in the BT reading auras/position
            }
            BotEvent::AuraChanged { .. } | BotEvent::UnitSpellCast { .. } => {
                // Encounter FSMs will read these via blackboard or future encounter module.
                // For now, events are consumed without side effects beyond clearing the queue.
            }
            BotEvent::PacketIn { .. } | BotEvent::PacketOut { .. } => {
                // Packet handlers will be added in later phases.
            }
        }
    }
}

// Allow accessing self_ field generated by bindgen (which uses C naming)
trait SnapSelfAccess {
    fn self_unit(&self) -> &crate::ffi::BotUnitSnapshot;
}
impl SnapSelfAccess for crate::ffi::BotWorldSnapshot {
    fn self_unit(&self) -> &crate::ffi::BotUnitSnapshot {
        &self.self_
    }
}
