[package]
name = "playerbot"
version.workspace = true
edition.workspace = true

[lib]
name = "playerbot_rs"
crate-type = ["staticlib", "rlib"]

[features]
default = []
vanilla = ["cmangos/vanilla"]
tbc = ["cmangos/tbc"]
wotlk = ["cmangos/wotlk"]

[dependencies]
cmangos = { path = "../cmangos" }
bitflags.workspace = true
arc-swap = "1"

[dev-dependencies]
cmangos = { path = "../cmangos", features = ["mock"] }

[lints]
workspace = true
